export default class ScheduleBuilder {
    protected cmd: string;
    protected cron: string;
    protected tz: string | undefined;
    constructor();
    command(command: string): ScheduleBuilder;
    timezone(timezone: string): ScheduleBuilder;
    everySecond(): void;
    everyTwoSeconds(): void;
    everyFiveSeconds(): void;
    everyTenSeconds(): void;
    everyFifteenSeconds(): void;
    everyTwentySeconds(): void;
    everyThirtySeconds(): void;
    everyMinute(): void;
    everyTwoMinutes(): void;
    everyThreeMinutes(): void;
    everyFourMinutes(): void;
    everyFiveMinutes(): void;
    everyTenMinutes(): void;
    everyFifteenMinutes(): void;
    everyThirtyMinutes(): void;
    hourly(): void;
    hourlyAt(minute: number): void;
    everyOddHour(minute?: number): void;
    everyTwoHours(minute?: number): void;
    everyThreeHours(minute?: number): void;
    everyFourHours(minute?: number): void;
    everySixHours(minute?: number): void;
    daily(): void;
    dailyAt(time: string): void;
    twiceDaily(h1: number, h2: number): void;
    twiceDailyAt(h1: number, h2: number, minute: number): void;
    weekly(): void;
    weeklyOn(day: number, time: string): void;
    monthly(): void;
    monthlyOn(day: number, time: string): void;
    twiceMonthly(d1: number, d2: number, time: string): void;
    yearly(): void;
    yearlyOn(month: number, day: number, time: string): void;
    private push;
    private timeToParts;
}
